In [1]:
# pip install numpy
# conda installnumpy
import numpy as np

In [6]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
np.zeros(5) #1 solo numeor para un arreglo

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros([5,5]) # 1 lista o tupla para una matriz de dimensiones
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [17]:
np.arange(2,5) # [2,20[

array([2, 3, 4])

In [19]:
np.arange(-12,1)

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [21]:
np.arange(0,20,2) #del [0,20[ en intervalos de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.arange(0,2.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [24]:
np.zeros(20).reshape(2,5,2)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
np.zeros(20).reshape(2,5,2).reshape(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [26]:
len(np.ones(12))

12

In [27]:
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones(12).reshape(4,3).shape

(4, 3)

In [30]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [31]:
#suma
a+b

array([15, 15, 15])

In [33]:
#resta
a-b

array([5, 5, 5])

In [34]:
b-a

array([-5, -5, -5])

In [35]:
#multiplicacion
a*b

array([50, 50, 50])

In [36]:
#division
a/2

array([5., 5., 5.])

In [38]:
# modulo
a % 3

array([1, 1, 1], dtype=int32)

In [150]:
muestra = np.arange(16).reshape(8,2)
muestra

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [151]:
respuesta_glucosa = muestra > 5
respuesta_glucosa2 = muestra < 14
respuesta_glucosa3 = muestra % 2 == 0

In [152]:
respuesta_glucosa
respuesta_glucosa2
respuesta_glucosa3

array([[ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False],
       [ True, False]])

In [153]:
respuestaF = respuesta_glucosa & respuesta_glucosa2 & respuesta_glucosa3
respuestaF
muestra[respuestaF]

array([ 6,  8, 10, 12])

In [154]:
#mayores a 5, menores a 14 y que sean pares

In [6]:
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [8]:
b = np.arange(4,8).reshape((2,2))
b

array([[4, 5],
       [6, 7]])

In [9]:
a.dot(b)

array([[ 6,  7],
       [26, 31]])

In [10]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
arreglo_doce.sum()

66

In [12]:
arreglo_doce.min()

0

In [13]:
arreglo_doce.max()

11

In [14]:
arreglo_doce[5:].sum()

56

In [15]:
arreglo_doce.reshape((3,2,2))

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [19]:
arreglo_doce.reshape(3,2,2).sum(axis = 0)

array([[12, 15],
       [18, 21]])

In [20]:
arreglo_doce.reshape(3,2,2).sum(axis = 1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [21]:
arreglo_doce.reshape(3,2,2).sum(axis = 2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])