In [1]:
import numpy as np

In [3]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [6]:
arreglo_radianes = arreglo_grados * np.pi / 180
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [7]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [8]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [9]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [23]:
numero_random = np.random.randint(
    11 # [0, 11[
)
numero_random

4

In [32]:
numero_random_negativo = np.random.randint(
    -9,  # [-9, 2[
    2
)
numero_random_negativo

-9

In [33]:
arreglo_random = np.random.randint(
    10,
    20,
    8
)
arreglo_random

array([15, 11, 18, 16, 19, 15, 16, 19])

In [39]:
np.random.rand(9) # 9 Elementos
np.random.rand(3,2) # 6 Elementos (3 x 2 dimensiones)

array([[0.02022387, 0.0486086 ],
       [0.60488577, 0.96511447],
       [0.51180613, 0.95767886]])

In [42]:
np.average(arreglo_random)

16.125

In [43]:
np.mean(arreglo_random)

16.125

In [44]:
np.median(arreglo_random)

16.0

In [45]:
np.std(arreglo_random)

2.4717149916606487

In [46]:
np.var(arreglo_random)

6.109375

In [47]:
arreglo_random.mean()

16.125