In [1]:
import numpy as np

In [3]:
arreglo = np.arange(11) **2
arreglo

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [4]:
arreglo[0:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [6]:
arreglo[2:-3]

array([ 4,  9, 16, 25, 36, 49], dtype=int32)

In [7]:
arreglo[0:6:2] #del 0 al 6 saltando de 2 en 2

array([ 0,  4, 16], dtype=int32)

In [8]:
arreglo[::-2]

array([100,  64,  36,  16,   4,   0], dtype=int32)